### ISSUE TITLE
Error during the install of bower dependencies

### ISSUE THREAD

**Issue by andrirad** [quarkslab/irma-ansible#111]
Hi,

I tried to deploy IRMA but I cannot get passed the install of bower dependencies. The bower binary is missing as far as I understand. Below is the output I got. I deleted the irma-frontend directory on the frontend server and relaunch the install but it did not change anything. 

The server is a debian 8.1.

<img width="362" alt="capture d ecran 2015-07-22 a 17 42 43" src="https://cloud.githubusercontent.com/assets/1461504/8829888/81a47090-3099-11e5-8be0-a2b9d444e5d4.png">

Thanks

**Comment by kamino** [comment]
:) debian 8.1 is not yet supported, sorry. There is something for debian 8.1 in the pipeline, please wait few more days.

**Comment by kamino** [comment]
@andrirad you should follow commits done on this branch: https://github.com/quarkslab/irma-ansible/tree/2130-move-to-debian-8. It works with the ``allinone_prod`` environment.

Do not hesitate to give us feedbacks if it works, and if something fails. Thanks in advance and happy beta-testing !

**Comment by andrirad** [comment]
@kamino I tried the `allinone_prod` environment and it worked. The VM is up and running. I submitted some files to make sure that the probes are working too :)

I got one error during the install of `rabbitmq-server`. See the screenshot for the complete output. Vagrant or the server could not fetch the updated apt files. I don't know why. To solve the problem, I manually executed `sudo aptitude update` on the server, then relaunched the provisionning. 

My next test is to deploy IRMA on different servers so I'll let you know how it goes !
 
<img width="604" alt="capture d ecran 2015-07-24 a 16 52 55" src="https://cloud.githubusercontent.com/assets/1461504/8877278/d17f324e-3224-11e5-94f5-9b51da80cbac.png">

**Comment by andrirad** [comment]
The `prod` environment works too. I had to disable three probes to make it works however: Avast, Zoner and EScan. Avast and Zoner required a license key and a license file so I assume the errors should be gone once the requirements are fulfilled. For EScan, the download link is not valid anymore. 
I guess the new link should be: 
"http://www.microworldsystems.com/download/linux/soho/deb/escan-antivirus-wks-7.0-18.amd64.deb"

<img width="714" alt="capture d ecran 2015-07-27 a 10 06 45" src="https://cloud.githubusercontent.com/assets/1461504/8909668/e76f37b0-3482-11e5-925d-9df29ec505e5.png">

**Comment by andrirad** [comment]
The provisioning of a production environment works too with Debian 8.1
`ansible-playbook -i hosts/example playbooks/playbook.yml -u vagrant -K`.

Thanks for all the work

**Comment by guillaumededrie** [comment]
Hi @andrirad,
Good Catch, We will make a pull request as soon as we will finish the Debian 8.1 provisioning.

Can we close the issue which was "Error during the install of bower dependencies"?

Regards,

**Comment by andrirad** [comment]
@guillaumededrie yes, you can
