### ISSUE TITLE
Virusblokada provisioning error, url not available

### ISSUE THREAD

**Issue by guillaumededrie** [quarkslab/irma-ansible#119]
The Virusblokada antivirus url (http://anti-virus.by/pub/vbacl-linux-3.12.10.6-20090601.tar.gz) is not available anymore. Need to investigate.

**Comment by Lastpixl** [comment]
Hello,
You'll find a few patches attached, fixing the URL, command line & installation procedure.
Inconveniently, github.com does not support .patch files as attachments, or sending patches over e-mail, so I'm attaching a zip.
[virusblokada_patches.zip](https://github.com/quarkslab/irma-ansible/files/403992/virusblokada_patches.zip)

**Comment by ch0k0bn** [comment]
was fixed in 5518a1005a75bda51ada18c1e442a39546638b04
just opened a new issue with ipv6 problem. (#147)

**Comment by Lastpixl** [comment]
Hi,
The install directory has changed in setup.sh. Now, the vbacl binary installs to the /opt/vba/vbacl/ folder.
You might want to apply my patch to roles/quarkslab.virusblokada/tasks/main.yml (virusblokada_commandline.patch).
