### ISSUE TITLE
/home/user1/.ssh/id-rsa.pub does not exist, but he is present!

### ISSUE THREAD

**Issue by dionis20** [quarkslab/irma-ansible#153]
![image](https://cloud.githubusercontent.com/assets/11872145/17802657/40f3cd60-65fa-11e6-953e-b40d8955c74c.png)

this file is present on every host! but why i got these errors?

**Comment by ch0k0bn** [comment]
Could you tell us which version of ansible you are using, which branch of irma-ansible and what kind of hosts you are trying to provision (virtual or physical machines) ?

**Comment by dionis20** [comment]
On Debian all is OK!
