### ISSUE TITLE
After reboot of physical server (probe) all modules can't find input files.

### ISSUE THREAD

**Issue by dionis20** [quarkslab/irma-ansible#154]
After reboot of physical server (probe) all modules can't find input files.

**Comment by ch0k0bn** [comment]
Could you share a log file ?

**Comment by dionis20** [comment]
Here are the logs:

![desktop](https://cloud.githubusercontent.com/assets/11872145/17958473/f587f72c-6aa2-11e6-8c58-e2a4b238f110.jpg)

rename it to zip, this is archive.

**Comment by dionis20** [comment]
[Desktop.docx](https://github.com/quarkslab/irma-ansible/files/436271/Desktop.docx)

**Comment by dionis20** [comment]
this is ZIP archive, i can't attach ZIP or TXT.

**Comment by dionis20** [comment]
[frontend.docx](https://github.com/quarkslab/irma-ansible/files/436386/frontend.docx)
Here are frontend logs.

**Comment by dionis20** [comment]
![image](https://cloud.githubusercontent.com/assets/11872145/17961463/8a3d0fe0-6ab4-11e6-928a-7d9f4ed65214.png)

**Comment by dionis20** [comment]
some samples scanned perfect, some samples triggered errors: no such file... in tmp dir
[VT report of errored sample](https://www.virustotal.com/en/file/bfa068f077e112d89c21b791b342aaf277a52d70efd375a26e471772614f627f/analysis/)

**Comment by dionis20** [comment]
reboot of servers was COLD.

**Comment by dionis20** [comment]
in one scan:
![image](https://cloud.githubusercontent.com/assets/11872145/17962566/2ab862da-6aba-11e6-9d07-237df956c77a.png)

2fdb28e8dec3396f986d8027bcd62e13:
![image](https://cloud.githubusercontent.com/assets/11872145/17962597/4cc8ceb4-6aba-11e6-9bd8-7eeb6e08dff0.png)

2fdb28e8dec3396f986d8027bcd62e13:
![image](https://cloud.githubusercontent.com/assets/11872145/17962631/7281c2f0-6aba-11e6-8bd9-d62670764fc4.png)

**Comment by ch0k0bn** [comment]
Could be linked to an AV not properly configured that delete virus file on access. Could you attach probe log file for one of the file that have no results ?

**Comment by dionis20** [comment]
yes, please:
[probe.docx](https://github.com/quarkslab/irma-ansible/files/436598/probe.docx)

**Comment by ch0k0bn** [comment]
could you manually try to copy a malware (EICAR file for example) on the probe machine to see if it is automatically detected and erased by one of the installed AV ?

**Comment by dionis20** [comment]
Yes, this is it. Some AV deleting samples.
And how can i turn off irma plugins?

**Comment by ch0k0bn** [comment]
It would be better to disable Real time scanner, could you check on the probe machine which AV has a service running and try to stop it ?

**Comment by dionis20** [comment]
i will try this. How can i disable some plugins? When i was installing yara, it was generate some errors and probe_app was stop starting. When i will write my own modules, how can i on/off it and some problem-plugins?

**Comment by ch0k0bn** [comment]
its a missing feature at the moment. As a temporary workaround, you could force the plugin to fail at load time by adding the same line as the one in the skeleton example https://github.com/quarkslab/irma-probe/blob/master/modules/custom/skeleton/plugin.py#L53 for each module you want to disable.

**Comment by dionis20** [comment]
Thanks! U've done big work! U're the best!
